---
title: "plots"
author: "Peilin Zhou"
date: "11/5/2021"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r, message = FALSE}
data("instacart")
```

Bar plot for most popular fresh fruits ordered in instacart
```{r}
fruit_plot = 
  instacart %>% 
  filter(aisle == "fresh fruits") %>% 
  group_by(product_name) %>% 
  summarise(
    n = n()
  ) %>% 
  filter(n > 2000) %>%
  mutate(product_name = fct_reorder(product_name, n)) %>% 
  plot_ly(
    x = ~product_name, y = ~n, type = "bar", color = ~product_name, colors = "viridis"
  ) %>% 
  layout(title = "Most Popular Fresh Fruits in Instacart")
fruit_plot
```

scatter+line plot for illustrating average order hour of a day in a week for white wines in instacart. 
```{r}
whi_wine_plot = instacart %>% 
  filter(aisle == "white wines") %>% 
  group_by(order_dow) %>% 
  summarise(
    average_hour = mean(order_hour_of_day)
  ) %>% 
  plot_ly(
    x = ~order_dow, y = ~average_hour, type = "scatter", mode = "lines"
  ) %>% 
  layout(
    title = "Average Order Hours of White Wines by Week",
    xaxis = list(title = 'Days of the Week')
  )
whi_wine_plot
```

```{r}
alcohol_plot = instacart %>% 
  filter(department == "alcohol") %>%
  plot_ly(
    x = ~aisle, y = ~order_hour_of_day, split = ~aisle, type = "violin", box = list(visible = T)
  ) %>% 
  layout(
    title = "Distribution of Order Hour of Alocohols in Instacart",
    xaxis = list(title = "Alcohol Types"),
    yaxis = list(title = "Order Hourder of a Day")
  )
alcohol_plot
```



